project:
  type: website
  output-dir: docs  #folder for github purposes

website:

# URL
  site-url: https://vivas014.github.io/personal-website/

# Title
  title: "Pablo Vivas"

# Search
  search: true

# Reader Mode
  reader-mode: false

# Navigation
  navbar:
    left:
      - href: index.qmd
        icon: house-fill
        text: Home
      - href: research.qmd
        icon: lightbulb-fill
        text: Teaching & Research
      # - href: index.qmd
      #   text: Side projects
      # - href: index.qmd
      #   text: Data Analysis
      # - href: about.qmd
      #   text: CV
    right: 
      - href: projects.qmd
        icon: paperclip
        text: Projects
      - href: blog.qmd
        icon: chat-right-text
        text: Blog
      # - href: cv/cv-pablo-vivas.pdf
      #   icon: filetype-pdf
      #   text: cv
      - icon: github
        href: https://github.com/vivas014
      - icon: twitter
        href: https://twitter.com/pablovivasc
      - icon: envelope
        href: mailto:vivas014@umn.edu

# logo  
#    logo: "imgs/logo-seeds.jpg"
#    logo-alt: "Alternative text

# color
    background: "#33658A" #Lapis Lazuli
    foreground: "#FFFFFF"

    # tools:
    #   - icon: twitter
    #     href: https://twitter.com/pablovivasc
    #   - icon: github
    #     href: https://github.com/vivas014

# footer
  page-footer: 
    border: true
    left: "Copyright 2023, Pablo Vivas" 
    # right: 
    #   - icon: github
    #     href: https://github.com/
    #   - icon: twitter 
    #     href: https://twitter.com/ 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



